{wall, wall, wall, wall, wall, wall, wall, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, floor, floor, floor, wall, floor, wall, wall},
    {wall, wall, wall, wall, wall, wall, wall, wall , wall},}